### ISSUE TITLE
test1

### ISSUE THREAD

**Issue by fcakyon** [ultralytics/assets#48]
what type of models exist in ultralytics?

**Comment by pderrenger** [comment]
Hi there! Thanks for reaching out. Ultralytics primarily focuses on YOLO (You Only Look Once) models for object detection tasks. This includes various versions, such as YOLOv3, YOLOv4, and more recently, YOLOv5 and YOLOv6, each offering improvements in speed and accuracy. You can explore more about these models and their details in our documentation at https://docs.ultralytics.com. Happy coding! 😊
