### ISSUE TITLE
Missing checkpoints for YOLOv9 and YOLOv10

### ISSUE THREAD

**Issue by triet1102** [ultralytics/assets#62]
Hello,

I have noticed that the checkpoints for YOLOv9 and YOLOv10 appear to be missing in **release 8.2.0**. Could you please confirm if they have been deleted?

Thank you in advance for your assistance.

**Comment by Krubico** [comment]
I am having this issue as well.

**Comment by pderrenger** [comment]
@Krubico hello,

Thank you for bringing this to our attention. The checkpoints for YOLOv9 and YOLOv10 should indeed be available. It's possible that there was an oversight or a temporary issue with the release.

Could you please confirm if you are using the latest version of the repository? Sometimes, updating to the most recent version can resolve such issues. If the problem persists, providing a minimum reproducible example would be very helpful for us to diagnose the issue more effectively. You can find guidance on how to create one here: [Minimum Reproducible Example](https://docs.ultralytics.com/help/minimum_reproducible_example).

We appreciate your patience and understanding. The YOLO community and the Ultralytics team are here to help!

**Comment by triet1102** [comment]
Hello @pderrenger, thank you for your response. 
I noticed that those checkpoints were uploaded shortly after I reported the issue.

**Comment by pderrenger** [comment]
Hello @triet1102,

Thank you for the update! I'm glad to hear that the checkpoints were uploaded shortly after your report. 🎉

If you encounter any further issues or have additional questions, please don't hesitate to reach out. The YOLO community and the Ultralytics team are always here to assist you.

Happy coding and best of luck with your projects!

Warm

**Comment by glenn-jocher** [comment]
Hello @triet1102, it seems the checkpoints were added after your report. If you have any further questions, feel free to ask.
